// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMov49ws6Dd-NsxoWcG2WW6U9lfyIj7sI',
    appId: '1:965800351312:web:9a4271dc31327a2d3d2355',
    messagingSenderId: '965800351312',
    projectId: 'todo-5f8ca',
    authDomain: 'todo-5f8ca.firebaseapp.com',
    storageBucket: 'todo-5f8ca.appspot.com',
    measurementId: 'G-Q3N3Q8GH0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs3BbTPGnIQvPeAs8F5Rk6hF6Lx8UpqGg',
    appId: '1:965800351312:android:9abd8a157beacc5e3d2355',
    messagingSenderId: '965800351312',
    projectId: 'todo-5f8ca',
    storageBucket: 'todo-5f8ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6reaHFzFvQRE0Q_WwwAKS0r6dJ1WDRjc',
    appId: '1:965800351312:ios:4a665ea6a90b653a3d2355',
    messagingSenderId: '965800351312',
    projectId: 'todo-5f8ca',
    storageBucket: 'todo-5f8ca.appspot.com',
    iosClientId: '965800351312-flb0q85kls51cf59lf2t4m6fq7m3rpff.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );
}
